/**
 * Enforcement Actions
 * Generate DMCA notices, violation reports, and legal documentation
 */

export interface ViolationReport {
  id: string
  ipId: string
  violationUrl: string
  violationType: 'copyright' | 'trademark' | 'watermark_removal'
  evidence: string[]
  reportedAt: string
  status: 'pending' | 'sent' | 'resolved'
}

export interface DMCANotice {
  id: string
  ipId: string
  violationUrl: string
  ownerName: string
  ownerAddress: string
  content: string
  generatedAt: string
}

/**
 * Generate DMCA Takedown Notice
 */
export function generateDMCANotice(params: {
  ipId: string
  violationUrl: string
  ownerName: string
  ownerAddress: string
  ipAssetName?: string
}): DMCANotice {
  const notice = {
    id: `dmca_${Date.now()}_${Math.random().toString(36).slice(2, 9)}`,
    ipId: params.ipId,
    violationUrl: params.violationUrl,
    ownerName: params.ownerName,
    ownerAddress: params.ownerAddress,
    content: generateDMCAContent(params),
    generatedAt: new Date().toISOString(),
  }

  return notice
}

/**
 * Generate DMCA notice content
 */
function generateDMCAContent(params: {
  ipId: string
  violationUrl: string
  ownerName: string
  ownerAddress: string
  ipAssetName?: string
}): string {
  return `
DMCA TAKEDOWN NOTICE

Date: ${new Date().toLocaleDateString()}

To Whom It May Concern:

I, ${params.ownerName}, am the owner of the intellectual property identified below:

IP Asset ID: ${params.ipId}
${params.ipAssetName ? `Asset Name: ${params.ipAssetName}` : ''}
Registered on: Story Protocol (Aeneid Testnet)

I have a good faith belief that the material identified below is infringing upon my copyright:

Infringing Material URL: ${params.violationUrl}

I request that you immediately remove or disable access to the infringing material.

I declare, under penalty of perjury, that:
1. I am the owner of the copyrighted work
2. The information in this notice is accurate
3. I have a good faith belief that the use of the material is not authorized

Owner Information:
Name: ${params.ownerName}
Address: ${params.ownerAddress}

Signature: [Digital Signature]

---
Generated by StorySeal IP Protection Suite
  `.trim()
}

/**
 * Create violation report
 */
export function createViolationReport(params: {
  ipId: string
  violationUrl: string
  violationType: 'copyright' | 'trademark' | 'watermark_removal'
  evidence: string[]
}): ViolationReport {
  return {
    id: `violation_${Date.now()}_${Math.random().toString(36).slice(2, 9)}`,
    ipId: params.ipId,
    violationUrl: params.violationUrl,
    violationType: params.violationType,
    evidence: params.evidence,
    reportedAt: new Date().toISOString(),
    status: 'pending',
  }
}

/**
 * Export violation report as PDF (mock - would use PDF library in production)
 */
export function exportViolationReport(report: ViolationReport): string {
  // In production, use a PDF library like jsPDF or pdfkit
  // For now, return formatted text
  return `
VIOLATION REPORT

Report ID: ${report.id}
IP Asset ID: ${report.ipId}
Violation URL: ${report.violationUrl}
Violation Type: ${report.violationType}
Reported At: ${new Date(report.reportedAt).toLocaleString()}
Status: ${report.status}

Evidence:
${report.evidence.map((e, i) => `${i + 1}. ${e}`).join('\n')}

---
Generated by StorySeal IP Protection Suite
  `.trim()
}

/**
 * Save violation reports
 */
export function saveViolationReport(report: ViolationReport): void {
  if (typeof window === 'undefined') return

  const stored = localStorage.getItem('storyseal_violation_reports')
  const reports: ViolationReport[] = stored ? JSON.parse(stored) : []
  reports.push(report)
  localStorage.setItem('storyseal_violation_reports', JSON.stringify(reports))
}

/**
 * Get all violation reports
 */
export function getViolationReports(): ViolationReport[] {
  if (typeof window === 'undefined') return []

  const stored = localStorage.getItem('storyseal_violation_reports')
  return stored ? JSON.parse(stored) : []
}

/**
 * Get violation reports by IP
 */
export function getViolationReportsByIP(ipId: string): ViolationReport[] {
  return getViolationReports().filter(r => r.ipId === ipId)
}

